//! C interface for the AES encryption plugin.
//!
//! Generated by the `declare_c_interface!` macro from `sz_common`.

use crate::aes_encryption::AesEncryption;

sz_common::declare_c_interface!(AesEncryption);
