//! C interface for the Dummy encryption plugin.
//!
//! Generated by the `declare_c_interface!` macro from `sz_common`.

use crate::dummy_encryption::DummyEncryption;

sz_common::declare_c_interface!(DummyEncryption);
