
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.aes]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.102"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-run"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bit-set]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.bit-vec]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.11.1"
criteria = "safe-to-run"

[[exemptions.block-padding]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.cbc]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.cipher]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.cpubits]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.4.1"
criteria = "safe-to-run"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-run"

[[exemptions.foldhash]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.17.0"
criteria = "safe-to-run"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.hybrid-array]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.id-arena]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.14.0"
criteria = "safe-to-run"

[[exemptions.inout]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.18"
criteria = "safe-to-run"

[[exemptions.leb128fmt]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.186"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.29"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.8.0"
criteria = "safe-to-run"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-run"

[[exemptions.prettyplease]]
version = "0.2.37"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-run"

[[exemptions.quote]]
version = "1.0.45"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-run"

[[exemptions.rand]]
version = "0.9.4"
criteria = "safe-to-run"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.rand_core]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.rand_xorshift]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.10"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "1.1.4"
criteria = "safe-to-run"

[[exemptions.rusty-fork]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.semver]]
version = "1.0.28"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-run"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.117"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.27.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.unicode-xid]]
version = "0.2.6"
criteria = "safe-to-run"

[[exemptions.wait-timeout]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.wasip2]]
version = "1.0.1+wasi-0.2.4"
criteria = "safe-to-run"

[[exemptions.wasip3]]
version = "0.4.0+wasi-0.3.0-rc-2026-01-06"
criteria = "safe-to-run"

[[exemptions.wasm-encoder]]
version = "0.244.0"
criteria = "safe-to-run"

[[exemptions.wasm-metadata]]
version = "0.244.0"
criteria = "safe-to-run"

[[exemptions.wasmparser]]
version = "0.244.0"
criteria = "safe-to-run"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-run"

[[exemptions.wit-bindgen]]
version = "0.46.0"
criteria = "safe-to-run"

[[exemptions.wit-bindgen]]
version = "0.51.0"
criteria = "safe-to-run"

[[exemptions.wit-bindgen-core]]
version = "0.51.0"
criteria = "safe-to-run"

[[exemptions.wit-bindgen-rust]]
version = "0.51.0"
criteria = "safe-to-run"

[[exemptions.wit-bindgen-rust-macro]]
version = "0.51.0"
criteria = "safe-to-run"

[[exemptions.wit-component]]
version = "0.244.0"
criteria = "safe-to-run"

[[exemptions.wit-parser]]
version = "0.244.0"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.48"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.48"
criteria = "safe-to-run"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-deploy"

[[exemptions.zmij]]
version = "1.0.21"
criteria = "safe-to-run"
