/* Senzing Encryption Plugin Interface
 *
 * AUTO-GENERATED by cbindgen from sz_common Rust crate — DO NOT EDIT.
 * Any change to the Rust FFI surface regenerates this file.
 * G2 engine keeps an exact copy; a build-time hash check catches drift.
 */

#ifndef SZ_ENCRYPT_PLUGIN_H
#define SZ_ENCRYPT_PLUGIN_H

#include <stddef.h>
#include <stdint.h>

/**
 * Error codes from the Senzing encryption plugin specification.
 * See: <https://github.com/Senzing/senzing-data-encryption-specification/blob/main/src/interface/g2EncryptionPluginInterface_defs.h>
 */
#define G2_ENCRYPTION_PLUGIN___SUCCESS 0

#define G2_ENCRYPTION_PLUGIN___SIMPLE_ERROR -1

#define G2_ENCRYPTION_PLUGIN___OUTPUT_BUFFER_SIZE_ERROR -5

#define G2_ENCRYPTION_PLUGIN___CRITICAL_ERROR -20

#define G2_ENCRYPTION_PLUGIN___FAILED_SIGNATURE_VALIDATION -30

/**
 * FFI-compatible parameter tuple matching `CParameterTuple` from the Senzing spec.
 */
typedef struct CParameterTuple {
  const char *paramName;
  const char *paramValue;
} CParameterTuple;

/**
 * FFI-compatible parameter list matching `CParameterList` from the Senzing spec.
 */
typedef struct CParameterList {
  struct CParameterTuple *paramTuples;
  size_t numParameters;
} CParameterList;

typedef int64_t (*G2EncryptionPluginInitPluginFuncPtr)(const struct CParameterList*,
                                                       char*,
                                                       size_t,
                                                       size_t*);

typedef int64_t (*G2EncryptionPluginClosePluginFuncPtr)(char*, size_t, size_t*);

typedef int64_t (*G2EncryptionPluginGetSignatureFuncPtr)(char*,
                                                         size_t,
                                                         size_t*,
                                                         char*,
                                                         size_t,
                                                         size_t*);

typedef int64_t (*G2EncryptionPluginValidateSignatureCompatibilityFuncPtr)(const char*,
                                                                           size_t,
                                                                           char*,
                                                                           size_t,
                                                                           size_t*);

typedef int64_t (*G2EncryptionPluginEncryptDataFieldFuncPtr)(const char*,
                                                             size_t,
                                                             char*,
                                                             size_t,
                                                             size_t*,
                                                             char*,
                                                             size_t,
                                                             size_t*);

typedef int64_t (*G2EncryptionPluginDecryptDataFieldFuncPtr)(const char*,
                                                             size_t,
                                                             char*,
                                                             size_t,
                                                             size_t*,
                                                             char*,
                                                             size_t,
                                                             size_t*);

typedef int64_t (*G2EncryptionPluginEncryptDataFieldDeterministicFuncPtr)(const char*,
                                                                          size_t,
                                                                          char*,
                                                                          size_t,
                                                                          size_t*,
                                                                          char*,
                                                                          size_t,
                                                                          size_t*);

typedef int64_t (*G2EncryptionPluginDecryptDataFieldDeterministicFuncPtr)(const char*,
                                                                          size_t,
                                                                          char*,
                                                                          size_t,
                                                                          size_t*,
                                                                          char*,
                                                                          size_t,
                                                                          size_t*);

#endif  /* SZ_ENCRYPT_PLUGIN_H */
